FROM almalinux:9.5

ARG CPUS=20

ENV CPUS=20

RUN dnf -y install 'dnf-command(config-manager)'

RUN dnf config-manager --set-enabled crb

RUN dnf -y install epel-release

RUN dnf -y update && dnf -y upgrade

RUN dnf -y group install "Development Tools"

RUN mkdir -p /cvmfs/icecube.opensciencegrid.org

RUN mkdir /usr/local/cvmfs_src

WORKDIR /usr/local/cvmfs_src

RUN git clone https://github.com/WIPACrepo/cvmfs.git --branch pass3 .

RUN python3 spack/build_v2.py py3-v4.4.0 --dest /cvmfs/icecube.opensciencegrid.org --src icecube.opensciencegrid.org --spack-target x86_64_v3


